function makeSTABrowser(recording)
    currentDir = pwd;
    [outputDir,outputFile] = getAnalysisOutputDir(recording);
    cd(outputDir);
    
    cleanup = onCleanup(@() cd(currentDir));
    
    gifs = dir('sta*.gif');
    gifs = {gifs.name};
    
    I = imread(gifs{1});
    y = size(I,1);
    x = size(I,2);

    html = sprintf([ ...
        '<html>\n' ...
            '<head>\n' ...
                '<script type="text/javascript">\n' ...
                    'var gifs = [' ...
                ]);

    for ii = 1:numel(gifs)
        html = [html '"' gifs{ii} '",']; %#ok<AGROW>
    end

    html = html(1:end-1);

    html = [html sprintf([        
                    '];\n' ...
                    'current = 0;\n' ...
                    'reg = /channel_([0-9]+)_cluster_([0-9]+)/;\n' ...
                    'function reloadSTA(increment) {\n' ...
                        'next = current + increment;\n' ...
                        'next = next < 0 ? gifs.length-1 : next >= gifs.length ? 0 : next;\n' ...
                        'setSTA(next);\n' ...
                    '}\n' ...
                    'function setSTA(next) {\n' ...
                        'current = next;\n' ...
                        'filename = gifs[current];\n' ...
                        'result = reg.exec(filename);\n' ...
                        'caption = document.getElementById("caption");\n' ...
                        'caption.innerHTML = "Channel " + result[1] + " Cluster " + result[2];\n' ...
                        'sta = document.getElementById("sta");\n' ...
                        'sta.src = filename;\n' ...
                    '}\n' ...
                '</script>\n' ...
            '</head>\n' ...
            '<body>\n' ...
                '<img style="image-rendering: crisp-edges" id="sta" src="' gifs{1} '" width="%d" height="%d" /><br />\n' ...
                '<span id="caption">Channel 12 Cluster 0</span><br />\n' ...
                '<a id="prev" href=# onclick="reloadSTA(-1)">Prev</a> <a id="curr" href=# onclick="reloadSTA(0)">Replay</a> <a id="next" href=# onclick="reloadSTA(+1)">Next</a>\n' ...
                '<br /><br />\n' ...
            ],x,y)];

    for ii = 1:numel(gifs)
        gif = gifs{ii};
        [~,~,~,channel_cluster] = regexp(gif,'channel_[0-9]+_cluster_[0-9]+');
        html = [html sprintf(['<a href=# onclick="setSTA(' num2str(ii-1) ')">' channel_cluster{1} '</a><br />\n'])]; %#ok<AGROW>
    end

    html = [html sprintf([ 
            '</body>\n' ...
        '</html>\n' ...
        ])];

    fout = fopen(['stabrowser_' outputFile '.html'],'w');
    fwrite(fout,html);
    fclose(fout);
    cd(currentDir);
end