n = 0;
parfor ll = 1:numel(I)
    tic;
x = double(I(ll));
% toc;
% tic;
[ii,jj,kk] = ind2sub(size(I),ll);
% toc;
% tic;
X{ll} = repmat([ii jj kk],x,1);
% toc;
% tic;
n = n+x;
toc;
end
%%
Y = zeros(N,3);
for ii = 1:10
    tic;
    Y(cumN(ii)+1:cumN(ii+1),:) = X{ii};
    toc;
end
%%
[A,B,C] = ind2sub(size(I),(1:numel(I))');
Z = [A B C];
f = @( ...
    maxMuY, ...
    maxMuX, ...
    maxMuT, ...
    maxSigmaY, ...
    maxSigmaX, ...
    maxSigmaT, ...
    minMuY, ...
    minMuX, ...
    minMuT, ...
    minSigmaY, ...
    minSigmaX, ...
    minSigmaT, ...
    maxK, ...
    minK, ...
    offset) ...
        mean( ...
            mean( ...
                mean( ...
                    ( ...
                        I -  ...
                        reshape( ...
                            maxK*mvnpdf(Z,[maxMuY maxMuX maxMuT],[maxSigmaY maxSigmaX maxSigmaT]) + ...
                            minK*mvnpdf(Z,[minMuY minMuX minMuT],[minSigmaY minSigmaX minSigmaT]) + ...
                            offset, ...
                            size(I) ...
                        ) ...
                    ).^2 ...
                ) ...
            ) ...
        );
        
x = {maxY maxX maxT minY minX minT 2 4 2 4 4 6 maxK minK offset};
e = f(x{:});